spring:
  config:
    import: "configserver:"
  profiles:
    active: dev

  application:
    name: COMMON-SERVICE
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  service:
    name: ${spring.application.name}
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIG-SERVER
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
management:
  endpoints:
    web:
      discovery:
        enabled: false
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0