spring:
  application:
    name: DISCOVERY-SERVICE
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  service:
    name: ${spring.application.name}
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      discovery:
        enabled: false
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0